<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container45qinx5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container45qinx5/appProdProjectContainer.php') {
    touch(__DIR__.'/Container45qinx5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container45qinx5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container45qinx5\appProdProjectContainer([
    'container.build_hash' => '45qinx5',
    'container.build_id' => '9d3eec9d',
    'container.build_time' => 1637342674,
], __DIR__.\DIRECTORY_SEPARATOR.'Container45qinx5');
