<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGfr4sxp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGfr4sxp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGfr4sxp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGfr4sxp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGfr4sxp\appProdProjectContainer([
    'container.build_hash' => 'Gfr4sxp',
    'container.build_id' => '9458811e',
    'container.build_time' => 1637166383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGfr4sxp');
