version: "3.9"

services:
  be_180109_prestashop:
    build:
      context: .
    ports:
      - "2437:443"
    networks:
      - admin-mongodb_default

networks:
  admin-mongodb_default:
    external:
      name: admin-mongodb_default
