version: '0.1'

services:
  db:
    build:
      context: context-db
    restart: always
    volumes:
      - ./shopdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changethisyoumoron

  presta:
    depends_on:
      - "db"
    build:
      context: context-presta
    ports:
      - "80:80"
    volumes:
      - ./ps-doc-root:/var/www/html