<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSm0jcvl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSm0jcvl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSm0jcvl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSm0jcvl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSm0jcvl\appProdProjectContainer([
    'container.build_hash' => 'Sm0jcvl',
    'container.build_id' => 'e86472ef',
    'container.build_time' => 1636207507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSm0jcvl');
