<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3rd6h8g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3rd6h8g/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3rd6h8g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3rd6h8g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3rd6h8g\appProdProjectContainer([
    'container.build_hash' => '3rd6h8g',
    'container.build_id' => '877d2eac',
    'container.build_time' => 1637183513,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3rd6h8g');
