<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOhejln0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOhejln0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOhejln0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOhejln0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOhejln0\appProdProjectContainer([
    'container.build_hash' => 'Ohejln0',
    'container.build_id' => '32e732d2',
    'container.build_time' => 1637166233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOhejln0');
