<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUu6vxel\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUu6vxel/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUu6vxel.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUu6vxel\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUu6vxel\appProdProjectContainer([
    'container.build_hash' => 'Uu6vxel',
    'container.build_id' => '0846d166',
    'container.build_time' => 1637186424,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUu6vxel');
